### ISSUE TITLE
Menu "Footer" is not accessible

### ISSUE THREAD

**Issue by kondor9** [droptica/droopler#107]
I can't edit the menu "Footer". Everytime I want to edit this menu I get an error "The website encountered an unexpected error. Please try again later.". Other menus can be edited without any problem. The problem occurs on a fresh install of Droopler 1.4. I don't know if the earlier versions of Droopler were also affected. I didn't check this.

**Comment by grzegorz-pietrzak-droptica** [comment]
We're on it!

**Comment by grzegorz-pietrzak-droptica** [comment]
Fixed in develop branch, to be deployed with 1.5.
