### ISSUE TITLE
Clean Install - Without demo content

### ISSUE THREAD

**Issue by shivkashyap** [droptica/droopler#118]
Is it possible to have an installation without demo content?

**Comment by shivkashyap** [comment]
BTW I am refeering to droopler_project

**Comment by grzegorz-pietrzak-droptica** [comment]
Hello, please put a `d_custom_init` module in your droopler_project starterkit and use the following code:

```php
/**
 * Alter content structure.
 * Implements hook_content_structure_alter()
 *
 * @param $structure
 *  The array with structure.
 *
 * @param $context
 *  Which structure array is this?
 */
function d_custom_init_content_structure_alter(&$structure, $context) {
  $structure = [];
}
```

**Comment by shivkashyap** [comment]
Perfect. Thanks a lot for your prompt response.

**Comment by shivkashyap** [comment]
d_custom_init worked. Is there anyway I can remove blogs examples. In the module d_blog module this is what I did to get rid of them. Is there any elegant way of doing it please?

* Altered Function below

*function d_blog_init_content_structure_alter(&$structure, $context) {
*  $path = drupal_get_path('module', 'd_blog_init') . '/pages';

*  if ($context == 'all') {
*    $structure['blog_post_1'] = ['file' => "$path/post_1.yml"];
*    $structure['blog_post_2'] = ['file' => "$path/post_2.yml"];
*    $structure['blog_post_3'] = ['file' => "$path/post_3.yml"];
*    $structure['blog_post_4'] = ['file' => "$path/post_4.yml"];
*    $structure['blog_post_5'] = ['file' => "$path/post_5.yml"];
*  }
*}
 */
function d_blog_init_content_structure_alter(&$structure, $context) {
  $path = drupal_get_path('module', 'd_blog_init') . '/pages';

  if ($context == 'all') {

  }
}

**Comment by ugintl** [comment]
@grzegorz-pietrzak-droptica did not work. I had to manually delete content.

**Comment by grzegorz-pietrzak-droptica** [comment]
@ugintl In 2.2 version there will be a functionality to choose demo content, https://www.drupal.org/project/droopler/issues/3155114
