### ISSUE TITLE
Links for unofficial modules for Droopler 

### ISSUE THREAD

**Issue by grzegorzbartman** [droptica/droopler#14]

**Comment by intelektron** [comment]
https://github.com/intelektron/i_p_gallery - simple gallery made with Colorbox

**Comment by intelektron** [comment]
https://github.com/intelektron/i_p_counters - counters for significant company numbers

**Comment by intelektron** [comment]
https://github.com/intelektron/d_p_carousel - Slick carousel with items scrolled

**Comment by grzegorz-pietrzak-droptica** [comment]
- https://github.com/droptica/d_p_gallery - simple gallery made with Colorbox
- https://github.com/droptica/d_p_side_embed - half text half embed (tested with YT and Google Maps)
- https://github.com/droptica/d_p_tiles - masonry gallery with colorbox
- https://github.com/droptica/d_p_side_tiles - half text half Masonry gallery

**Comment by grzegorz-pietrzak-droptica** [comment]
The above paragraphs are in core now.
