### ISSUE TITLE
d_lang_dropdown.js selector proplem

### ISSUE THREAD

**Issue by solody** [droptica/droopler#177]
Shoud not use absolute block ID, because it depend on the active theme name.
It should be class selector here:

`var  $languageswitcher = $('.block.block-language:not(dropdown)');`

**Comment by solody** [comment]
https://github.com/droptica/droopler/pull/178 pull please.

**Comment by grzegorz-pietrzak-droptica** [comment]
Hello @solody, thanks for pointing this out. We will merge this into the `devel` branch and include in 1.5 version.
