### ISSUE TITLE
Block configurations should move to sub theme's config/optional directory. 

### ISSUE THREAD

**Issue by solody** [droptica/droopler#179]
When I implement a new sub theme, and enable the d_product module, the facts sidebar block does't appear.
This is because block configurations depend on specific theme.

**Comment by solody** [comment]
https://github.com/droptica/droopler_project/pull/62 pull please

**Comment by grzegorz-pietrzak-droptica** [comment]
Hello @solody, as I wrote in the PR, in 1.5 version of Droopler we will insert these blocks in the `.install` file - to be able to match them to any theme with sidebar.
