### ISSUE TITLE
Admin Toolbar 2.x

### ISSUE THREAD

**Issue by michal-borek** [droptica/droopler#425]
https://github.com/droptica/droopler/blob/4576360c3011808103c4461519d3135dbc4fecc3/composer.json#L25

Why Droopler not utilizes the lastest Admin Toolbar module? Any reason?

**Comment by rafal-sereda-droptica** [comment]
Hello @michal-borek, thanks for reaching us. 
I'm happy to announce that Droopler composer.json was updated recently and the admin_toolbar version was changed to 2.0.
