### ISSUE TITLE
d_social_media form links not being saved.

### ISSUE THREAD

**Issue by alexrayu** [droptica/droopler#426]
In current beta2, social media links are not being saved in the d_social_media settings form (`\Drupal\d_social_media\Form\ConfigurationForm::submitForm()`) reason being that the config is being addressed with each link but not saved until all links have been set, probably resulting in multiple unsaved config instances.

Saving the config at once resolves the issue. Please consider.

```
  public function submitForm(array &$form, FormStateInterface $form_state) {
    parent::submitForm($form, $form_state);
    $values = [];
    foreach ($this->getMediaNames() as $name) {
      $values["link_$name"] = $form_state->getValue("link_$name");
      $this->config(self::CONFIGURATION_NAME)
        ->set("link_$name", $form_state->getValue("link_$name"))->save();
    }
  }

```

**Comment by rafal-sereda-droptica** [comment]
Hello @alexrayu, thanks for reaching us.
Today I did some tests. For me, it looks like Social Links are saving properly. Changes are visible after the cache refresh. 
I tested on the development version, but there was no significant changes made to the d_social_media module recently.
Could you maybe confirm it still occurs in your environment? 

![image](https://user-images.githubusercontent.com/37533838/80353911-544be580-8876-11ea-9c54-a67ba5ca4c8e.png)
![image](https://user-images.githubusercontent.com/37533838/80354019-7a718580-8876-11ea-8b9a-df1cdb29a821.png)

**Comment by alexrayu** [comment]
Hello Rafal,
I can no longer reproduce the issue. Likely a false alarm.
Thanks for looking into it!
Best Regards,
Alexei.
