### ISSUE TITLE
Implement a pathauto pattern for blog posts

### ISSUE THREAD

**Issue by budda** [droptica/droopler#45]
It would be nice if the blog content type had a pathauto pattern provided by default

Suggestion: `blog/[node:title]`

**Comment by grzegorz-pietrzak-droptica** [comment]
Thanks for noticing that! We'll let you know when it is fixed, in the meantime please change your pathauto setings in admin panel.

**Comment by grzegorz-pietrzak-droptica** [comment]
Fixed in develop branch, to be deployed with 1.5.
