### ISSUE TITLE
No web folder created when installing droopler

### ISSUE THREAD

**Issue by valica** [droptica/droopler#482]
Hello,
Using the installation procedure presented on your website, this leads to a all in one folder. In fact, no web folder is created.
This comes from composer.json. I will update it on my side and make a test.

**Comment by valica** [comment]
I understood this issue. The procedure mentioned on your website for droopler installation asks to install the no_web branch and there the composer.json is wrong.
The master is OK.
This issue can be then solved if you fix the procedure here: https://www.droptica.com/blog/installation-and-updating-droopler-nutshell/
Kind regards,
Vlad

**Comment by valica** [comment]
Base don my comment above, I propose to close the issue after the procedure fix.

**Comment by rafal-sereda-droptica** [comment]
Hello @valica, thank you for reporting this. To be honest, we didn't think about updating old blog posts describing methods for creating the Droopler project, but it's not a bad idea to make some order and maybe at least clean some old branches. We'll be looking over old instructions and doing some cleanups.

Cheers!

**Comment by grzegorz-pietrzak-droptica** [comment]
Hello, the `no_web` branch is not supported anymore, since few version "web" directory is always created. @valica please let us know if you notice any problems with it.
