### ISSUE TITLE
 ReferenceError: primordials is not defined when compiling SCSS

### ISSUE THREAD

**Issue by valica** [droptica/droopler#483]
Hello,

When trying to compile the SCSS (gulp compile) using the method 1 of the installation procedure specified on your site, I have this error:

ReferenceError: primordials is not defined
  at fs.js:35:5
    at req_ (/Users/vlad/Sites/droopler-test/droopler_project/themes/custom/droopler_subtheme/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/vlad/Sites/droopler-test/droopler_project/themes/custom/droopler_subtheme/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/vlad/Sites/droopler-test/droopler_project/themes/custom/droopler_subtheme/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)

Kind regards,
Vlad

**Comment by valica** [comment]
Aligning everything on the master branch, it leads to a dependent library missing which is bootstrap. Adding the missing dependency, make it building OK.
HTH,
Vlad VALICA

**Comment by alexrayu** [comment]
Hello Vlad, this may be related to the Node version. Please make sure you are using Node 11.
```
$ nvm use 11
$ npm install
$ gulp compile
```

**Comment by valica** [comment]
Hi Alex,
In fact the problem was the tutorial on your site about how to install droopler.
One of the steps says to clone git but the branch "web" is specified there. The problem was seen only on the web branch. Cloning the master, everything is OK.
Node version is OK

**Comment by alexrayu** [comment]
I am a bit confused - I don't think they have "web" branch for Droopler. I also made some overviews but I don't think I made a video how to install it. 

I am glad you found a way to fix your issue! If that issue no longer exists, please consider closing the ticket.

**Comment by valica** [comment]
Here: https://www.droptica.com/blog/installation-and-updating-droopler-nutshell/
you give steps to follow for installing droopler.

Using Method1, we have that:
git clone -b no_web https://github.com/droptica/droopler_project
(ok, the branch is called "no_web")
That's the problem origin. That branch is not good. Consider removing the branch and then it's OK.

**Comment by alexrayu** [comment]
I see. I am not Droptica, so they will actually need to respond about this. Glad you figured out how to make it work though!

**Comment by rafal-sereda-droptica** [comment]
I think we have an understanding here @valica. Thanks for reporting the issue of old posts. If it comes to the referenced error message, it is related to Node/Gulp versions - as @alexrayu suggested. I think we can close this issue.

**Comment by valica** [comment]
OK to close it. The user guide about how to build droopler distribution from sources shall be updated.
