### ISSUE TITLE
Mega menu produces capitalize items which is not good is many countries

### ISSUE THREAD

**Issue by valica** [droptica/droopler#491]
Hello,

Using the Mega Menu module, which is built-in in droopler now, it produces only capitalize menu items and that's not OK, it should be configured if yes or no.
In the meanwhile, I've made the analysis and I saw the problem is not coming from we-mega-menu but from on scss of droopler_theme which has created styling for mega menu.

Origin is in __menu_design.scss L:187
text-transform: capitalize;

Pay attention there is a subsequent style for uppercase and that's also not good.
I think you can have whatever behaviour you prefer as default and add the mega-menu configuration panel for adapting to needs. This way everybody's happy.

Kind regards,

Vlad VALICA

**Comment by rafal-sereda-droptica** [comment]
Hello, thanks for reaching us.
If it comes to capitalized menu items - it's a matter of styling (as you pointed out), so you can adjust how things look by creating your subtheme with the desired styling. 
Maybe in the future, we'll think about some configuration panel, but for now, we consider CSS as enough.
Cheers!

**Comment by valica** [comment]
That's right, I can do that in the subtheme.
Thanx for the reply.
