### ISSUE TITLE
Close area does not go away on screen resize

### ISSUE THREAD

**Issue by alexrayu** [droptica/droopler#636]
1. Open the products page. https://droopler-demo.droptica.com/products
2. Narrow the browser to mobile width. 
3. Click "Filters".
4. Widen the browser to desktop width.
The filters are gone but the black semi-translucent div.close-area remains visible.

https://i.imgur.com/XtJvHU5.png

**Comment by alexrayu** [comment]
Please check out this patch. I made it form root folder - if you prefer I rather made it from the theme folder please tell.
[fix-close-area.txt](https://github.com/droptica/droopler/files/5141488/fix-close-area.txt)

**Comment by grzegorz-pietrzak-droptica** [comment]
Hello, thanks for reporting the issue, we will deploy the fix it to the upcoming 2.2 release.

**Comment by alexrayu** [comment]
Thanks!
