### ISSUE TITLE
Overwritting content & menus

### ISSUE THREAD

**Issue by partikus** [droptica/droopler#677]
Hello there!

Loading a full dataset from the droopler profile is a pain. Thanks to @grzegorz-pietrzak-droptica I've found [the ticket](https://www.drupal.org/project/droopler/issues/3130450) suggesting to create the custom init data module overriding the structure.
That works pretty well.  [d_custom_init_0.zip](https://github.com/droptica/droopler/files/5529734/d_custom_init_0.zip) Thanks 👏 👍 

Still, some loading content's subparts are unclear to me. 

1. How can I override navigations? 
2. Why I cannot delete the main navigation's item, can I? An error: `This link is provided by the d_product module. The title and path cannot be edited.`
<img width="1132" alt="image" src="https://user-images.githubusercontent.com/1732227/98926008-0c6d7280-24d7-11eb-9750-bfb79b8929f2.png">
3. What's the best approach for loading & keeping content in the droopler's project?

Thanks in advance!

**Comment by grzegorz-pietrzak-droptica** [comment]
Hello,

Actually in the upcoming new release you will be able to choose if you want the example content (and if you want to install d_product and d_blog), so this **custom init** method will no longer be needed. The process of installation is completely refactored.

If you don't need d_product related functionalities, you can safely turn it off, and delete its content types, taxonomies and views.

**Comment by partikus** [comment]
@grzegorz-pietrzak-droptica yep, `v2.2` sounds promising but could you keep this `c_custom_init` installation step in to avoid BC breaks, please?

**Comment by grzegorz-pietrzak-droptica** [comment]
@partikus The hook to alter content will still work in next versions, so custom inits are not in danger :-)
