### ISSUE TITLE
Error when installing profile: Modules required but not found

### ISSUE THREAD

**Issue by Abdulee** [droptica/droopler#780]
Hello,
Its my first time trying to install a drupal profile.. I have moved the droopler files downloaded from [here](https://www.drupal.org/project/droopler) into /profiles/contrib/droopler
The droopler installer starts in browser and then throws the following error. 
```
Required modules
Required modules not found.
The following modules are required but were not found. Move them into the appropriate modules subdirectory, such as /modules. Missing modules:

  Admin_toolbarAdmin_toolbar_toolsAdvaggAdvagg_modAdvagg_js_minifyAdvagg_css_minifyChecklistapiColorboxConfig_updateEntity_reference_revisionsFeaturesFeatures_uiGeysirLazyLink_attributesLinkitMetatagParagraphsPathautoRedirectSimple_sitemapSvg_imageSvg_image_responsiveWe_megamenu

```

I did run composer install in the /profiles/contrib/droopler 
Am I supposed to install this modules manually one by one?

**Comment by grzegorz-pietrzak-droptica** [comment]
Hi, for future reference - we recommend using `droptica/droopler` instead of `drupal/droopler` composer package. The latter one has dependency issues caused by drupal.org.
