### ISSUE TITLE
Reference content display

### ISSUE THREAD

**Issue by Beercik** [droptica/droopler#786]
Reference content (d_p_reference_content) shows unpublished content

![Zrzut ekranu 2022-01-19 o 22 57 17](https://user-images.githubusercontent.com/5422049/150220594-18ad2138-f330-4451-96a0-cc90a669fd7a.png)

**Comment by grzegorz-pietrzak-droptica** [comment]
Thanks for reporting the issue, we're on it

**Comment by grzegorz-pietrzak-droptica** [comment]
The issue was fixed on the `develop` branch of Droopler, it will be a part of 3.1.0. Thanks again for noticing this!
