### ISSUE TITLE
JSON.parse error during load page

### ISSUE THREAD

**Issue by patranger** [droptica/droopler#810]
I installed Droopler following the instructions below with PHP 8
https://github.com/droptica/droopler_project/blob/master/README.md

but when I open the page, this message pops up

`(function () {var settingsElement = document.querySelector ('head> script [type = "application / json"] [data-drupal-selector = "drupal-settings-json"], body> script [type = "application / json "] [data-drupal-selector =" drupal-settings-json "] '); window.drupalSettings = {}; if (settingsElement! == null) {window.drupalSettings = JSON.parse (settingsElement.textContent); }}) ()`

**Comment by grzegorz-pietrzak-droptica** [comment]
Hello, this is because of AdvAgg module aggregation pl PHP 8.x. Currently, we are searching for the solution. Most probably, some PHP module is missing.

**Comment by grzegorz-pietrzak-droptica** [comment]
The latest Droopler from `develop` branch fixes these issues. It works seamlessly with PHP 8.1.
