### ISSUE TITLE
Bugs during installation

### ISSUE THREAD

**Issue by patranger** [droptica/droopler#811]
I installed Droopler following the instructions below with PHP 8

https://github.com/droptica/droopler_project/blob/master/README.md

I launched the website and a Drupal-specific installer appeared. After configuring all the parameters in the last two steps, installing the modules and something else, such errors appeared

Warning: Undefined array key "d_custom_init" in Drupal\Core\Extension\ModuleInstaller->install() (line 125 of core/lib/Drupal/Core/Extension/ModuleInstaller.php).
    Drupal\Core\Extension\ModuleInstaller->install(Array, 1) (Line: 83)
    Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array) (Line: 44)
    droopler_install()
    call_user_func_array('droopler_install', Array) (Line: 392)
    Drupal\Core\Extension\ModuleHandler->invoke('droopler', 'install', Array) (Line: 362)
    Drupal\Core\Extension\ModuleInstaller->install(Array, ) (Line: 83)
    Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array, ) (Line: 1658)
    install_install_profile(Array) (Line: 700)
    install_run_task(Array, Array) (Line: 571)
    install_run_tasks(Array, NULL) (Line: 119)
    install_drupal(Object) (Line: 48)

    Warning: Attempt to read property "info" on null in Drupal\Core\Extension\ModuleInstaller->install() (line 125 of core/lib/Drupal/Core/Extension/ModuleInstaller.php).

    Drupal\Core\Extension\ModuleInstaller->install(Array, 1) (Line: 83)
    Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array) (Line: 44)
    droopler_install()
    call_user_func_array('droopler_install', Array) (Line: 392)
    Drupal\Core\Extension\ModuleHandler->invoke('droopler', 'install', Array) (Line: 362)
    Drupal\Core\Extension\ModuleInstaller->install(Array, ) (Line: 83)
    Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array, ) (Line: 1658)
    install_install_profile(Array) (Line: 700)
    install_run_task(Array, Array) (Line: 571)
    install_run_tasks(Array, NULL) (Line: 119)
    install_drupal(Object) (Line: 48)

    Warning: Trying to access array offset on value of type null in Drupal\Core\Extension\ModuleInstaller->install() (line 125 of core/lib/Drupal/Core/Extension/ModuleInstaller.php).

    Drupal\Core\Extension\ModuleInstaller->install(Array, 1) (Line: 83)
    Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array) (Line: 44)
    droopler_install()
    call_user_func_array('droopler_install', Array) (Line: 392)
    Drupal\Core\Extension\ModuleHandler->invoke('droopler', 'install', Array) (Line: 362)
    Drupal\Core\Extension\ModuleInstaller->install(Array, ) (Line: 83)
    Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array, ) (Line: 1658)
    install_install_profile(Array) (Line: 700)
    install_run_task(Array, Array) (Line: 571)
    install_run_tasks(Array, NULL) (Line: 119)
    install_drupal(Object) (Line: 48)

**Comment by grzegorz-pietrzak-droptica** [comment]
Hello, on Friday we released `3.1.0-rc1` version that has improved PHP8 compatibility. If you are still experiencing problems - it may be the solution.
