### ISSUE TITLE
4.0 Branch Install Step 2 fails

### ISSUE THREAD

**Issue by 35develr** [droptica/droopler#896]
Got error 'PHP message: PHP Fatal error:  Declaration of Drupal\\d_frontend_editing\\Controller\\FrontendEditingController::paragraphAddPage($parent_type, $parent, $parent_field_name, $current_paragraph, $before): array must be compatible with Drupal\\frontend_editing\\Controller\\FrontendEditingController::paragraphAddPage($parent_type, $parent, $parent_field_name, $current_paragraph, $before, Symfony\\Component\\HttpFoundation\\Request $request) in /mnt/HC_Volume_100239027/www/html/tinyhouse/web/profiles/contrib/droopler/modules/custom/d_frontend_editing/src/Controller/FrontendEditingController.php on line 19', referer: https://XXXXXXXXX/core/install.php?rewrite=ok&profile=droopler&langcode=de&id=1&op=start

**Comment by 35develr** [comment]
Solution:

Add  $request to function paragraphAddPage in
/web/profiles/contrib/droopler/modules/custom/d_frontend_editing/src/Controller/FrontendEditingController.php on line 19
```

  public function paragraphAddPage($parent_type, $parent, $parent_field_name, $current_paragraph, $before, $request): array {
    $build = parent::paragraphAddPage($parent_type, $parent, $parent_field_name, $current_paragraph, $before,  $request);
```

**Comment by jsamulski** [comment]
Hi. Yes, we already updated the code. We will try to release `alpha2` today with this and a few other updates.

**Comment by jsamulski** [comment]
The new `4.0.0-alpha2` has been released. It contains the fox for this issue.

Thanks and all the best :)
